// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ad_collaborators.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listAdCollaboratorsByCompanyID = `-- name: ListAdCollaboratorsByCompanyID :many
SELECT id, company_id, niche_id, ad_id, user_id, role, commission_pct_min, commission_pct_max, created_at, updated_at
FROM ad_collaborators
WHERE company_id = $1
ORDER BY created_at DESC, role, user_id
`

func (q *Queries) ListAdCollaboratorsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]AdCollaborator, error) {
	rows, err := q.db.Query(ctx, listAdCollaboratorsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdCollaborator{}
	for rows.Next() {
		var i AdCollaborator
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdID,
			&i.UserID,
			&i.Role,
			&i.CommissionPctMin,
			&i.CommissionPctMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdCollaboratorsByNicheID = `-- name: ListAdCollaboratorsByNicheID :many
SELECT id, company_id, niche_id, ad_id, user_id, role, commission_pct_min, commission_pct_max, created_at, updated_at
FROM ad_collaborators
WHERE company_id = $1
  AND niche_id = $2
ORDER BY created_at DESC, role, user_id
`

type ListAdCollaboratorsByNicheIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
}

func (q *Queries) ListAdCollaboratorsByNicheID(ctx context.Context, arg ListAdCollaboratorsByNicheIDParams) ([]AdCollaborator, error) {
	rows, err := q.db.Query(ctx, listAdCollaboratorsByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdCollaborator{}
	for rows.Next() {
		var i AdCollaborator
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdID,
			&i.UserID,
			&i.Role,
			&i.CommissionPctMin,
			&i.CommissionPctMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
