// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ad_metric_snapshots.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listAdMetricSnapshotsByCompanyID = `-- name: ListAdMetricSnapshotsByCompanyID :many
SELECT id, company_id, niche_id, ad_id, snapshot_date, impressions, clicks, spend, cpc, cpm, ctr, reach, frequency, hook_rate, body_rate, view_page, initiate_checkout, cost_per_ic, fetched_at, created_at
FROM ad_metric_snapshots
WHERE company_id = $1
ORDER BY snapshot_date DESC, ad_id
`

func (q *Queries) ListAdMetricSnapshotsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]AdMetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listAdMetricSnapshotsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdMetricSnapshot{}
	for rows.Next() {
		var i AdMetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdID,
			&i.SnapshotDate,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Cpc,
			&i.Cpm,
			&i.Ctr,
			&i.Reach,
			&i.Frequency,
			&i.HookRate,
			&i.BodyRate,
			&i.ViewPage,
			&i.InitiateCheckout,
			&i.CostPerIc,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdMetricSnapshotsByNicheID = `-- name: ListAdMetricSnapshotsByNicheID :many
SELECT id, company_id, niche_id, ad_id, snapshot_date, impressions, clicks, spend, cpc, cpm, ctr, reach, frequency, hook_rate, body_rate, view_page, initiate_checkout, cost_per_ic, fetched_at, created_at
FROM ad_metric_snapshots
WHERE company_id = $1
  AND niche_id = $2
ORDER BY snapshot_date DESC, ad_id
`

type ListAdMetricSnapshotsByNicheIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
}

func (q *Queries) ListAdMetricSnapshotsByNicheID(ctx context.Context, arg ListAdMetricSnapshotsByNicheIDParams) ([]AdMetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listAdMetricSnapshotsByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdMetricSnapshot{}
	for rows.Next() {
		var i AdMetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdID,
			&i.SnapshotDate,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Cpc,
			&i.Cpm,
			&i.Ctr,
			&i.Reach,
			&i.Frequency,
			&i.HookRate,
			&i.BodyRate,
			&i.ViewPage,
			&i.InitiateCheckout,
			&i.CostPerIc,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
