// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getAdByExternalIDOrName = `-- name: GetAdByExternalIDOrName :one
SELECT id, company_id, niche_id, adset_id, external_id, name, name_parsed, status, rejection_reason, validated_at, utm_source, utm_campaign, utm_content, utm_term, created_at, updated_at
FROM ads
WHERE company_id = $1
  AND (
    external_id = $2
    OR lower(name) = lower($3)
    OR lower(COALESCE(utm_content, '')) = lower($3)
  )
ORDER BY
  CASE
    WHEN external_id = $2 THEN 0
    WHEN lower(name) = lower($3) THEN 1
    ELSE 2
  END
LIMIT 1
`

type GetAdByExternalIDOrNameParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ExternalID string    `json:"external_id"`
	Lower      string    `json:"lower"`
}

func (q *Queries) GetAdByExternalIDOrName(ctx context.Context, arg GetAdByExternalIDOrNameParams) (Ad, error) {
	row := q.db.QueryRow(ctx, getAdByExternalIDOrName, arg.CompanyID, arg.ExternalID, arg.Lower)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.AdsetID,
		&i.ExternalID,
		&i.Name,
		&i.NameParsed,
		&i.Status,
		&i.RejectionReason,
		&i.ValidatedAt,
		&i.UtmSource,
		&i.UtmCampaign,
		&i.UtmContent,
		&i.UtmTerm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdCollaboratorsByAdID = `-- name: ListAdCollaboratorsByAdID :many
SELECT id, company_id, niche_id, ad_id, user_id, role, commission_pct_min, commission_pct_max, created_at, updated_at
FROM ad_collaborators
WHERE ad_id = $1
ORDER BY role, created_at
`

func (q *Queries) ListAdCollaboratorsByAdID(ctx context.Context, adID uuid.UUID) ([]AdCollaborator, error) {
	rows, err := q.db.Query(ctx, listAdCollaboratorsByAdID, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdCollaborator{}
	for rows.Next() {
		var i AdCollaborator
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdID,
			&i.UserID,
			&i.Role,
			&i.CommissionPctMin,
			&i.CommissionPctMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdsByCompanyID = `-- name: ListAdsByCompanyID :many
SELECT id, company_id, niche_id, adset_id, external_id, name, name_parsed, status, rejection_reason, validated_at, utm_source, utm_campaign, utm_content, utm_term, created_at, updated_at
FROM ads
WHERE company_id = $1
ORDER BY updated_at DESC, name
`

func (q *Queries) ListAdsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Ad, error) {
	rows, err := q.db.Query(ctx, listAdsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ad{}
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdsetID,
			&i.ExternalID,
			&i.Name,
			&i.NameParsed,
			&i.Status,
			&i.RejectionReason,
			&i.ValidatedAt,
			&i.UtmSource,
			&i.UtmCampaign,
			&i.UtmContent,
			&i.UtmTerm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdsByNicheID = `-- name: ListAdsByNicheID :many
SELECT id, company_id, niche_id, adset_id, external_id, name, name_parsed, status, rejection_reason, validated_at, utm_source, utm_campaign, utm_content, utm_term, created_at, updated_at
FROM ads
WHERE company_id = $1
  AND niche_id = $2
ORDER BY updated_at DESC, name
`

type ListAdsByNicheIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
}

func (q *Queries) ListAdsByNicheID(ctx context.Context, arg ListAdsByNicheIDParams) ([]Ad, error) {
	rows, err := q.db.Query(ctx, listAdsByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ad{}
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.AdsetID,
			&i.ExternalID,
			&i.Name,
			&i.NameParsed,
			&i.Status,
			&i.RejectionReason,
			&i.ValidatedAt,
			&i.UtmSource,
			&i.UtmCampaign,
			&i.UtmContent,
			&i.UtmTerm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdCollaborator = `-- name: UpsertAdCollaborator :one
INSERT INTO ad_collaborators (
    company_id,
    niche_id,
    ad_id,
    user_id,
    role,
    commission_pct_min,
    commission_pct_max
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (ad_id, user_id, role)
DO UPDATE SET
    commission_pct_min = EXCLUDED.commission_pct_min,
    commission_pct_max = EXCLUDED.commission_pct_max,
    updated_at = now()
RETURNING id, company_id, niche_id, ad_id, user_id, role, commission_pct_min, commission_pct_max, created_at, updated_at
`

type UpsertAdCollaboratorParams struct {
	CompanyID        uuid.UUID       `json:"company_id"`
	NicheID          uuid.UUID       `json:"niche_id"`
	AdID             uuid.UUID       `json:"ad_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Role             string          `json:"role"`
	CommissionPctMin decimal.Decimal `json:"commission_pct_min"`
	CommissionPctMax decimal.Decimal `json:"commission_pct_max"`
}

func (q *Queries) UpsertAdCollaborator(ctx context.Context, arg UpsertAdCollaboratorParams) (AdCollaborator, error) {
	row := q.db.QueryRow(ctx, upsertAdCollaborator,
		arg.CompanyID,
		arg.NicheID,
		arg.AdID,
		arg.UserID,
		arg.Role,
		arg.CommissionPctMin,
		arg.CommissionPctMax,
	)
	var i AdCollaborator
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.AdID,
		&i.UserID,
		&i.Role,
		&i.CommissionPctMin,
		&i.CommissionPctMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
