// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commission_rules.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listCommissionRuleCandidates = `-- name: ListCommissionRuleCandidates :many
SELECT id, company_id, niche_id, user_id, offer_id, role, percentage_min, percentage_max, rule_type, priority, active, created_at, updated_at
FROM commission_rules
WHERE company_id = $1
  AND role = $2
  AND active = TRUE
  AND (niche_id IS NULL OR niche_id = $3)
  AND (user_id IS NULL OR user_id = $4)
  AND (
    offer_id IS NULL
    OR ($5::uuid IS NOT NULL AND offer_id = $5::uuid)
  )
ORDER BY
  CASE
    WHEN user_id IS NOT NULL AND offer_id IS NOT NULL THEN 1
    WHEN user_id IS NOT NULL THEN 2
    WHEN offer_id IS NOT NULL THEN 3
    ELSE 4
  END,
  priority ASC,
  created_at ASC
`

type ListCommissionRuleCandidatesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Role      string      `json:"role"`
	NicheID   pgtype.UUID `json:"niche_id"`
	UserID    pgtype.UUID `json:"user_id"`
	OfferID   pgtype.UUID `json:"offer_id"`
}

func (q *Queries) ListCommissionRuleCandidates(ctx context.Context, arg ListCommissionRuleCandidatesParams) ([]CommissionRule, error) {
	rows, err := q.db.Query(ctx, listCommissionRuleCandidates,
		arg.CompanyID,
		arg.Role,
		arg.NicheID,
		arg.UserID,
		arg.OfferID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionRule{}
	for rows.Next() {
		var i CommissionRule
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.UserID,
			&i.OfferID,
			&i.Role,
			&i.PercentageMin,
			&i.PercentageMax,
			&i.RuleType,
			&i.Priority,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommissionEntry = `-- name: UpsertCommissionEntry :one
INSERT INTO commission_entries (
    company_id,
    niche_id,
    transaction_id,
    user_id,
    role,
    base_amount,
    commission_pct,
    commission_value,
    status,
    adjustment_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (transaction_id, user_id, role)
DO UPDATE SET
    niche_id = EXCLUDED.niche_id,
    base_amount = EXCLUDED.base_amount,
    commission_pct = EXCLUDED.commission_pct,
    commission_value = EXCLUDED.commission_value,
    status = EXCLUDED.status,
    adjustment_reason = EXCLUDED.adjustment_reason,
    updated_at = now()
RETURNING id, company_id, niche_id, transaction_id, user_id, commission_period_id, role, base_amount, commission_pct, commission_value, status, adjustment_reason, created_at, updated_at
`

type UpsertCommissionEntryParams struct {
	CompanyID        uuid.UUID       `json:"company_id"`
	NicheID          pgtype.UUID     `json:"niche_id"`
	TransactionID    uuid.UUID       `json:"transaction_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Role             string          `json:"role"`
	BaseAmount       decimal.Decimal `json:"base_amount"`
	CommissionPct    decimal.Decimal `json:"commission_pct"`
	CommissionValue  decimal.Decimal `json:"commission_value"`
	Status           string          `json:"status"`
	AdjustmentReason *string         `json:"adjustment_reason"`
}

func (q *Queries) UpsertCommissionEntry(ctx context.Context, arg UpsertCommissionEntryParams) (CommissionEntry, error) {
	row := q.db.QueryRow(ctx, upsertCommissionEntry,
		arg.CompanyID,
		arg.NicheID,
		arg.TransactionID,
		arg.UserID,
		arg.Role,
		arg.BaseAmount,
		arg.CommissionPct,
		arg.CommissionValue,
		arg.Status,
		arg.AdjustmentReason,
	)
	var i CommissionEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.TransactionID,
		&i.UserID,
		&i.CommissionPeriodID,
		&i.Role,
		&i.BaseAmount,
		&i.CommissionPct,
		&i.CommissionValue,
		&i.Status,
		&i.AdjustmentReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
