// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commission_entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listCommissionEntriesByCompanyID = `-- name: ListCommissionEntriesByCompanyID :many
SELECT id, company_id, niche_id, transaction_id, user_id, commission_period_id, role, base_amount, commission_pct, commission_value, status, adjustment_reason, created_at, updated_at
FROM commission_entries
WHERE company_id = $1
ORDER BY created_at DESC, user_id
`

func (q *Queries) ListCommissionEntriesByCompanyID(ctx context.Context, companyID uuid.UUID) ([]CommissionEntry, error) {
	rows, err := q.db.Query(ctx, listCommissionEntriesByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionEntry{}
	for rows.Next() {
		var i CommissionEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.TransactionID,
			&i.UserID,
			&i.CommissionPeriodID,
			&i.Role,
			&i.BaseAmount,
			&i.CommissionPct,
			&i.CommissionValue,
			&i.Status,
			&i.AdjustmentReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommissionEntriesByNicheID = `-- name: ListCommissionEntriesByNicheID :many
SELECT id, company_id, niche_id, transaction_id, user_id, commission_period_id, role, base_amount, commission_pct, commission_value, status, adjustment_reason, created_at, updated_at
FROM commission_entries
WHERE company_id = $1
  AND niche_id = $2
ORDER BY created_at DESC, user_id
`

type ListCommissionEntriesByNicheIDParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	NicheID   pgtype.UUID `json:"niche_id"`
}

func (q *Queries) ListCommissionEntriesByNicheID(ctx context.Context, arg ListCommissionEntriesByNicheIDParams) ([]CommissionEntry, error) {
	rows, err := q.db.Query(ctx, listCommissionEntriesByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionEntry{}
	for rows.Next() {
		var i CommissionEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.TransactionID,
			&i.UserID,
			&i.CommissionPeriodID,
			&i.Role,
			&i.BaseAmount,
			&i.CommissionPct,
			&i.CommissionValue,
			&i.Status,
			&i.AdjustmentReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
