// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Ad struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	NicheID         uuid.UUID          `json:"niche_id"`
	AdsetID         uuid.UUID          `json:"adset_id"`
	ExternalID      string             `json:"external_id"`
	Name            string             `json:"name"`
	NameParsed      json.RawMessage    `json:"name_parsed"`
	Status          string             `json:"status"`
	RejectionReason *string            `json:"rejection_reason"`
	ValidatedAt     pgtype.Timestamptz `json:"validated_at"`
	UtmSource       *string            `json:"utm_source"`
	UtmCampaign     *string            `json:"utm_campaign"`
	UtmContent      *string            `json:"utm_content"`
	UtmTerm         *string            `json:"utm_term"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AdAccount struct {
	ID                    uuid.UUID          `json:"id"`
	CompanyID             uuid.UUID          `json:"company_id"`
	NicheID               uuid.UUID          `json:"niche_id"`
	PlatformIntegrationID pgtype.UUID        `json:"platform_integration_id"`
	ExternalID            string             `json:"external_id"`
	Name                  string             `json:"name"`
	Currency              string             `json:"currency"`
	Timezone              *string            `json:"timezone"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AdCollaborator struct {
	ID               uuid.UUID          `json:"id"`
	CompanyID        uuid.UUID          `json:"company_id"`
	NicheID          uuid.UUID          `json:"niche_id"`
	AdID             uuid.UUID          `json:"ad_id"`
	UserID           uuid.UUID          `json:"user_id"`
	Role             string             `json:"role"`
	CommissionPctMin decimal.Decimal    `json:"commission_pct_min"`
	CommissionPctMax decimal.Decimal    `json:"commission_pct_max"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AdMetricSnapshot struct {
	ID               uuid.UUID          `json:"id"`
	CompanyID        uuid.UUID          `json:"company_id"`
	NicheID          uuid.UUID          `json:"niche_id"`
	AdID             uuid.UUID          `json:"ad_id"`
	SnapshotDate     pgtype.Date        `json:"snapshot_date"`
	Impressions      int64              `json:"impressions"`
	Clicks           int64              `json:"clicks"`
	Spend            decimal.Decimal    `json:"spend"`
	Cpc              decimal.Decimal    `json:"cpc"`
	Cpm              decimal.Decimal    `json:"cpm"`
	Ctr              decimal.Decimal    `json:"ctr"`
	Reach            int64              `json:"reach"`
	Frequency        decimal.Decimal    `json:"frequency"`
	HookRate         decimal.Decimal    `json:"hook_rate"`
	BodyRate         decimal.Decimal    `json:"body_rate"`
	ViewPage         int64              `json:"view_page"`
	InitiateCheckout int64              `json:"initiate_checkout"`
	CostPerIc        decimal.Decimal    `json:"cost_per_ic"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Adset struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	NicheID    uuid.UUID          `json:"niche_id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	NicheID     uuid.UUID          `json:"niche_id"`
	AdAccountID uuid.UUID          `json:"ad_account_id"`
	ExternalID  string             `json:"external_id"`
	Name        string             `json:"name"`
	Objective   *string            `json:"objective"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CommissionEntry struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	NicheID            pgtype.UUID        `json:"niche_id"`
	TransactionID      uuid.UUID          `json:"transaction_id"`
	UserID             uuid.UUID          `json:"user_id"`
	CommissionPeriodID pgtype.UUID        `json:"commission_period_id"`
	Role               string             `json:"role"`
	BaseAmount         decimal.Decimal    `json:"base_amount"`
	CommissionPct      decimal.Decimal    `json:"commission_pct"`
	CommissionValue    decimal.Decimal    `json:"commission_value"`
	Status             string             `json:"status"`
	AdjustmentReason   *string            `json:"adjustment_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CommissionPeriod struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	NicheID     pgtype.UUID        `json:"niche_id"`
	PeriodMonth pgtype.Date        `json:"period_month"`
	Status      string             `json:"status"`
	ClosedBy    pgtype.UUID        `json:"closed_by"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	Notes       *string            `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CommissionRule struct {
	ID            uuid.UUID          `json:"id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	NicheID       pgtype.UUID        `json:"niche_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OfferID       pgtype.UUID        `json:"offer_id"`
	Role          string             `json:"role"`
	PercentageMin decimal.Decimal    `json:"percentage_min"`
	PercentageMax decimal.Decimal    `json:"percentage_max"`
	RuleType      string             `json:"rule_type"`
	Priority      int32              `json:"priority"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	LegalName   *string            `json:"legal_name"`
	TaxID       *string            `json:"tax_id"`
	TaxRate     decimal.Decimal    `json:"tax_rate"`
	Plan        string             `json:"plan"`
	Active      bool               `json:"active"`
	SuspendedAt pgtype.Timestamptz `json:"suspended_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CompanyFeatureFlag struct {
	CompanyID uuid.UUID          `json:"company_id"`
	Feature   string             `json:"feature"`
	Enabled   bool               `json:"enabled"`
	EnabledBy pgtype.UUID        `json:"enabled_by"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
}

type ImpersonationSession struct {
	ID                 uuid.UUID          `json:"id"`
	SystemUserID       uuid.UUID          `json:"system_user_id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	ImpersonatedUserID uuid.UUID          `json:"impersonated_user_id"`
	Reason             string             `json:"reason"`
	IpAddress          string             `json:"ip_address"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
}

type Nich struct {
	ID        uuid.UUID          `json:"id"`
	CompanyID uuid.UUID          `json:"company_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	TaxRate   *decimal.Decimal   `json:"tax_rate"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NicheUser struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	NicheID    uuid.UUID          `json:"niche_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Active     bool               `json:"active"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type Offer struct {
	ID        uuid.UUID          `json:"id"`
	CompanyID uuid.UUID          `json:"company_id"`
	NicheID   uuid.UUID          `json:"niche_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PerformanceGoal struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	NicheID     pgtype.UUID        `json:"niche_id"`
	OfferID     pgtype.UUID        `json:"offer_id"`
	PeriodMonth pgtype.Date        `json:"period_month"`
	ProfitGoal  decimal.Decimal    `json:"profit_goal"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PlatformIntegration struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	NicheID           pgtype.UUID        `json:"niche_id"`
	Platform          string             `json:"platform"`
	Name              string             `json:"name"`
	Active            bool               `json:"active"`
	WebhookToken      string             `json:"webhook_token"`
	WebhookSecret     *string            `json:"webhook_secret"`
	AccessToken       *string            `json:"access_token"`
	RefreshToken      *string            `json:"refresh_token"`
	ExternalAccountID *string            `json:"external_account_id"`
	Metadata          json.RawMessage    `json:"metadata"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	NicheID    uuid.UUID          `json:"niche_id"`
	OfferID    uuid.UUID          `json:"offer_id"`
	Platform   string             `json:"platform"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	Active     bool               `json:"active"`
	Metadata   json.RawMessage    `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SystemAuditLog struct {
	ID              uuid.UUID          `json:"id"`
	SystemUserID    pgtype.UUID        `json:"system_user_id"`
	ImpersonationID pgtype.UUID        `json:"impersonation_id"`
	Action          string             `json:"action"`
	TargetType      *string            `json:"target_type"`
	TargetID        pgtype.UUID        `json:"target_id"`
	Payload         []byte             `json:"payload"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SystemUser struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	TotpSecret   string             `json:"totp_secret"`
	Active       bool               `json:"active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp  *string            `json:"last_login_ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	NicheID           pgtype.UUID        `json:"niche_id"`
	SourceDeliveryID  pgtype.UUID        `json:"source_delivery_id"`
	Platform          string             `json:"platform"`
	PlatformTxID      string             `json:"platform_tx_id"`
	EventType         string             `json:"event_type"`
	Amount            decimal.Decimal    `json:"amount"`
	UpsellAmount      decimal.Decimal    `json:"upsell_amount"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	AttributionStatus string             `json:"attribution_status"`
	BuyerEmail        *string            `json:"buyer_email"`
	BuyerName         *string            `json:"buyer_name"`
	AdID              pgtype.UUID        `json:"ad_id"`
	OfferID           pgtype.UUID        `json:"offer_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	RawPayload        json.RawMessage    `json:"raw_payload"`
	UtmParams         json.RawMessage    `json:"utm_params"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	Code         *string            `json:"code"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID                    uuid.UUID          `json:"id"`
	CompanyID             uuid.UUID          `json:"company_id"`
	PlatformIntegrationID pgtype.UUID        `json:"platform_integration_id"`
	Platform              string             `json:"platform"`
	CompanyToken          string             `json:"company_token"`
	ExternalEventID       *string            `json:"external_event_id"`
	PayloadHash           string             `json:"payload_hash"`
	Signature             *string            `json:"signature"`
	Headers               json.RawMessage    `json:"headers"`
	Payload               json.RawMessage    `json:"payload"`
	Status                string             `json:"status"`
	ErrorMessage          *string            `json:"error_message"`
	Retries               int32              `json:"retries"`
	ReceivedAt            pgtype.Timestamptz `json:"received_at"`
	QueuedAt              pgtype.Timestamptz `json:"queued_at"`
	ProcessedAt           pgtype.Timestamptz `json:"processed_at"`
}
