// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: niches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listNichesByCompanyID = `-- name: ListNichesByCompanyID :many
SELECT id, company_id, name, slug, tax_rate, active, created_at, updated_at
FROM niches
WHERE company_id = $1
ORDER BY name
`

func (q *Queries) ListNichesByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Nich, error) {
	rows, err := q.db.Query(ctx, listNichesByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Nich{}
	for rows.Next() {
		var i Nich
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Slug,
			&i.TaxRate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
