// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: offers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOfferByCode = `-- name: GetOfferByCode :one
SELECT id, company_id, niche_id, code, name, active, created_at, updated_at
FROM offers
WHERE company_id = $1
  AND niche_id = $2
  AND code = $3
LIMIT 1
`

type GetOfferByCodeParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
	Code      string    `json:"code"`
}

func (q *Queries) GetOfferByCode(ctx context.Context, arg GetOfferByCodeParams) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferByCode, arg.CompanyID, arg.NicheID, arg.Code)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOffersByCompanyID = `-- name: ListOffersByCompanyID :many
SELECT id, company_id, niche_id, code, name, active, created_at, updated_at
FROM offers
WHERE company_id = $1
ORDER BY name
`

func (q *Queries) ListOffersByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Offer, error) {
	rows, err := q.db.Query(ctx, listOffersByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Offer{}
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersByNicheID = `-- name: ListOffersByNicheID :many
SELECT id, company_id, niche_id, code, name, active, created_at, updated_at
FROM offers
WHERE company_id = $1
  AND niche_id = $2
ORDER BY name
`

type ListOffersByNicheIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
}

func (q *Queries) ListOffersByNicheID(ctx context.Context, arg ListOffersByNicheIDParams) ([]Offer, error) {
	rows, err := q.db.Query(ctx, listOffersByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Offer{}
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
