// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: platform_integrations.sql

package sqlc

import (
	"context"
)

const getPlatformIntegrationByWebhookToken = `-- name: GetPlatformIntegrationByWebhookToken :one
SELECT id, company_id, niche_id, platform, name, active, webhook_token, webhook_secret, access_token, refresh_token, external_account_id, metadata, last_synced_at, created_at, updated_at
FROM platform_integrations
WHERE platform = $1
  AND webhook_token = $2
  AND active = TRUE
LIMIT 1
`

type GetPlatformIntegrationByWebhookTokenParams struct {
	Platform     string `json:"platform"`
	WebhookToken string `json:"webhook_token"`
}

func (q *Queries) GetPlatformIntegrationByWebhookToken(ctx context.Context, arg GetPlatformIntegrationByWebhookTokenParams) (PlatformIntegration, error) {
	row := q.db.QueryRow(ctx, getPlatformIntegrationByWebhookToken, arg.Platform, arg.WebhookToken)
	var i PlatformIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.Platform,
		&i.Name,
		&i.Active,
		&i.WebhookToken,
		&i.WebhookSecret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExternalAccountID,
		&i.Metadata,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
