// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getProductByPlatformExternalID = `-- name: GetProductByPlatformExternalID :one
SELECT id, company_id, niche_id, offer_id, platform, external_id, name, active, metadata, created_at, updated_at
FROM products
WHERE company_id = $1
  AND platform = $2
  AND external_id = $3
LIMIT 1
`

type GetProductByPlatformExternalIDParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
}

func (q *Queries) GetProductByPlatformExternalID(ctx context.Context, arg GetProductByPlatformExternalIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByPlatformExternalID, arg.CompanyID, arg.Platform, arg.ExternalID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.OfferID,
		&i.Platform,
		&i.ExternalID,
		&i.Name,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
