// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	GetAdByExternalIDOrName(ctx context.Context, arg GetAdByExternalIDOrNameParams) (Ad, error)
	GetOfferByCode(ctx context.Context, arg GetOfferByCodeParams) (Offer, error)
	GetPlatformIntegrationByWebhookToken(ctx context.Context, arg GetPlatformIntegrationByWebhookTokenParams) (PlatformIntegration, error)
	GetProductByPlatformExternalID(ctx context.Context, arg GetProductByPlatformExternalIDParams) (Product, error)
	GetWebhookDeliveryContext(ctx context.Context, id uuid.UUID) (GetWebhookDeliveryContextRow, error)
	ListAdCollaboratorsByAdID(ctx context.Context, adID uuid.UUID) ([]AdCollaborator, error)
	ListAdCollaboratorsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]AdCollaborator, error)
	ListAdCollaboratorsByNicheID(ctx context.Context, arg ListAdCollaboratorsByNicheIDParams) ([]AdCollaborator, error)
	ListAdMetricSnapshotsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]AdMetricSnapshot, error)
	ListAdMetricSnapshotsByNicheID(ctx context.Context, arg ListAdMetricSnapshotsByNicheIDParams) ([]AdMetricSnapshot, error)
	ListAdsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Ad, error)
	ListAdsByNicheID(ctx context.Context, arg ListAdsByNicheIDParams) ([]Ad, error)
	ListCommissionEntriesByCompanyID(ctx context.Context, companyID uuid.UUID) ([]CommissionEntry, error)
	ListCommissionEntriesByNicheID(ctx context.Context, arg ListCommissionEntriesByNicheIDParams) ([]CommissionEntry, error)
	ListCommissionRuleCandidates(ctx context.Context, arg ListCommissionRuleCandidatesParams) ([]CommissionRule, error)
	ListNichesByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Nich, error)
	ListOffersByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Offer, error)
	ListOffersByNicheID(ctx context.Context, arg ListOffersByNicheIDParams) ([]Offer, error)
	ListTransactionsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Transaction, error)
	ListTransactionsByNicheID(ctx context.Context, arg ListTransactionsByNicheIDParams) ([]Transaction, error)
	ListUsersByCodes(ctx context.Context, arg ListUsersByCodesParams) ([]User, error)
	ListUsersByCompanyID(ctx context.Context, companyID uuid.UUID) ([]User, error)
	ListUsersByNicheID(ctx context.Context, arg ListUsersByNicheIDParams) ([]User, error)
	MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error
	MarkWebhookDeliveryProcessed(ctx context.Context, id uuid.UUID) error
	MarkWebhookDeliveryQueued(ctx context.Context, id uuid.UUID) error
	UpsertAdCollaborator(ctx context.Context, arg UpsertAdCollaboratorParams) (AdCollaborator, error)
	UpsertCommissionEntry(ctx context.Context, arg UpsertCommissionEntryParams) (CommissionEntry, error)
	UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
