// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listTransactionsByCompanyID = `-- name: ListTransactionsByCompanyID :many
SELECT id, company_id, niche_id, source_delivery_id, platform, platform_tx_id, event_type, amount, upsell_amount, currency, status, attribution_status, buyer_email, buyer_name, ad_id, offer_id, product_id, raw_payload, utm_params, occurred_at, created_at, updated_at
FROM transactions
WHERE company_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListTransactionsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.SourceDeliveryID,
			&i.Platform,
			&i.PlatformTxID,
			&i.EventType,
			&i.Amount,
			&i.UpsellAmount,
			&i.Currency,
			&i.Status,
			&i.AttributionStatus,
			&i.BuyerEmail,
			&i.BuyerName,
			&i.AdID,
			&i.OfferID,
			&i.ProductID,
			&i.RawPayload,
			&i.UtmParams,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByNicheID = `-- name: ListTransactionsByNicheID :many
SELECT id, company_id, niche_id, source_delivery_id, platform, platform_tx_id, event_type, amount, upsell_amount, currency, status, attribution_status, buyer_email, buyer_name, ad_id, offer_id, product_id, raw_payload, utm_params, occurred_at, created_at, updated_at
FROM transactions
WHERE company_id = $1
  AND niche_id = $2
ORDER BY occurred_at DESC
`

type ListTransactionsByNicheIDParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	NicheID   pgtype.UUID `json:"niche_id"`
}

func (q *Queries) ListTransactionsByNicheID(ctx context.Context, arg ListTransactionsByNicheIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NicheID,
			&i.SourceDeliveryID,
			&i.Platform,
			&i.PlatformTxID,
			&i.EventType,
			&i.Amount,
			&i.UpsellAmount,
			&i.Currency,
			&i.Status,
			&i.AttributionStatus,
			&i.BuyerEmail,
			&i.BuyerName,
			&i.AdID,
			&i.OfferID,
			&i.ProductID,
			&i.RawPayload,
			&i.UtmParams,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO transactions (
    company_id,
    niche_id,
    source_delivery_id,
    platform,
    platform_tx_id,
    event_type,
    amount,
    upsell_amount,
    currency,
    status,
    attribution_status,
    buyer_email,
    buyer_name,
    ad_id,
    offer_id,
    product_id,
    raw_payload,
    utm_params,
    occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (company_id, platform, platform_tx_id)
DO UPDATE SET
    niche_id = EXCLUDED.niche_id,
    source_delivery_id = EXCLUDED.source_delivery_id,
    event_type = EXCLUDED.event_type,
    amount = EXCLUDED.amount,
    upsell_amount = EXCLUDED.upsell_amount,
    currency = EXCLUDED.currency,
    status = EXCLUDED.status,
    attribution_status = EXCLUDED.attribution_status,
    buyer_email = EXCLUDED.buyer_email,
    buyer_name = EXCLUDED.buyer_name,
    ad_id = EXCLUDED.ad_id,
    offer_id = EXCLUDED.offer_id,
    product_id = EXCLUDED.product_id,
    raw_payload = EXCLUDED.raw_payload,
    utm_params = EXCLUDED.utm_params,
    occurred_at = EXCLUDED.occurred_at,
    updated_at = now()
RETURNING id, company_id, niche_id, source_delivery_id, platform, platform_tx_id, event_type, amount, upsell_amount, currency, status, attribution_status, buyer_email, buyer_name, ad_id, offer_id, product_id, raw_payload, utm_params, occurred_at, created_at, updated_at
`

type UpsertTransactionParams struct {
	CompanyID         uuid.UUID          `json:"company_id"`
	NicheID           pgtype.UUID        `json:"niche_id"`
	SourceDeliveryID  pgtype.UUID        `json:"source_delivery_id"`
	Platform          string             `json:"platform"`
	PlatformTxID      string             `json:"platform_tx_id"`
	EventType         string             `json:"event_type"`
	Amount            decimal.Decimal    `json:"amount"`
	UpsellAmount      decimal.Decimal    `json:"upsell_amount"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	AttributionStatus string             `json:"attribution_status"`
	BuyerEmail        *string            `json:"buyer_email"`
	BuyerName         *string            `json:"buyer_name"`
	AdID              pgtype.UUID        `json:"ad_id"`
	OfferID           pgtype.UUID        `json:"offer_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	RawPayload        json.RawMessage    `json:"raw_payload"`
	UtmParams         json.RawMessage    `json:"utm_params"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertTransaction,
		arg.CompanyID,
		arg.NicheID,
		arg.SourceDeliveryID,
		arg.Platform,
		arg.PlatformTxID,
		arg.EventType,
		arg.Amount,
		arg.UpsellAmount,
		arg.Currency,
		arg.Status,
		arg.AttributionStatus,
		arg.BuyerEmail,
		arg.BuyerName,
		arg.AdID,
		arg.OfferID,
		arg.ProductID,
		arg.RawPayload,
		arg.UtmParams,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NicheID,
		&i.SourceDeliveryID,
		&i.Platform,
		&i.PlatformTxID,
		&i.EventType,
		&i.Amount,
		&i.UpsellAmount,
		&i.Currency,
		&i.Status,
		&i.AttributionStatus,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.AdID,
		&i.OfferID,
		&i.ProductID,
		&i.RawPayload,
		&i.UtmParams,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
