// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listUsersByCodes = `-- name: ListUsersByCodes :many
SELECT id, company_id, code, full_name, email, password_hash, role, active, last_login_at, created_at, updated_at
FROM users
WHERE company_id = $1
  AND code = ANY($2::text[])
  AND active = TRUE
ORDER BY full_name
`

type ListUsersByCodesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   []string  `json:"column_2"`
}

func (q *Queries) ListUsersByCodes(ctx context.Context, arg ListUsersByCodesParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByCodes, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.FullName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCompanyID = `-- name: ListUsersByCompanyID :many
SELECT id, company_id, code, full_name, email, password_hash, role, active, last_login_at, created_at, updated_at
FROM users
WHERE company_id = $1
  AND active = TRUE
ORDER BY role, full_name
`

func (q *Queries) ListUsersByCompanyID(ctx context.Context, companyID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.FullName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByNicheID = `-- name: ListUsersByNicheID :many
SELECT u.id, u.company_id, u.code, u.full_name, u.email, u.password_hash, u.role, u.active, u.last_login_at, u.created_at, u.updated_at
FROM users u
INNER JOIN niche_users nu
    ON nu.user_id = u.id
   AND nu.company_id = u.company_id
WHERE u.company_id = $1
  AND nu.niche_id = $2
  AND u.active = TRUE
  AND nu.active = TRUE
ORDER BY u.role, u.full_name
`

type ListUsersByNicheIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	NicheID   uuid.UUID `json:"niche_id"`
}

func (q *Queries) ListUsersByNicheID(ctx context.Context, arg ListUsersByNicheIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByNicheID, arg.CompanyID, arg.NicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.FullName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
