// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook_deliveries.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    company_id,
    platform_integration_id,
    platform,
    company_token,
    external_event_id,
    payload_hash,
    signature,
    headers,
    payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, platform_integration_id, platform, company_token, external_event_id, payload_hash, signature, headers, payload, status, error_message, retries, received_at, queued_at, processed_at
`

type CreateWebhookDeliveryParams struct {
	CompanyID             uuid.UUID       `json:"company_id"`
	PlatformIntegrationID pgtype.UUID     `json:"platform_integration_id"`
	Platform              string          `json:"platform"`
	CompanyToken          string          `json:"company_token"`
	ExternalEventID       *string         `json:"external_event_id"`
	PayloadHash           string          `json:"payload_hash"`
	Signature             *string         `json:"signature"`
	Headers               json.RawMessage `json:"headers"`
	Payload               json.RawMessage `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.CompanyID,
		arg.PlatformIntegrationID,
		arg.Platform,
		arg.CompanyToken,
		arg.ExternalEventID,
		arg.PayloadHash,
		arg.Signature,
		arg.Headers,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PlatformIntegrationID,
		&i.Platform,
		&i.CompanyToken,
		&i.ExternalEventID,
		&i.PayloadHash,
		&i.Signature,
		&i.Headers,
		&i.Payload,
		&i.Status,
		&i.ErrorMessage,
		&i.Retries,
		&i.ReceivedAt,
		&i.QueuedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getWebhookDeliveryContext = `-- name: GetWebhookDeliveryContext :one
SELECT webhook_deliveries.id, webhook_deliveries.company_id, webhook_deliveries.platform_integration_id, webhook_deliveries.platform, webhook_deliveries.company_token, webhook_deliveries.external_event_id, webhook_deliveries.payload_hash, webhook_deliveries.signature, webhook_deliveries.headers, webhook_deliveries.payload, webhook_deliveries.status, webhook_deliveries.error_message, webhook_deliveries.retries, webhook_deliveries.received_at, webhook_deliveries.queued_at, webhook_deliveries.processed_at, platform_integrations.id, platform_integrations.company_id, platform_integrations.niche_id, platform_integrations.platform, platform_integrations.name, platform_integrations.active, platform_integrations.webhook_token, platform_integrations.webhook_secret, platform_integrations.access_token, platform_integrations.refresh_token, platform_integrations.external_account_id, platform_integrations.metadata, platform_integrations.last_synced_at, platform_integrations.created_at, platform_integrations.updated_at
FROM webhook_deliveries
LEFT JOIN platform_integrations ON platform_integrations.id = webhook_deliveries.platform_integration_id
WHERE webhook_deliveries.id = $1
LIMIT 1
`

type GetWebhookDeliveryContextRow struct {
	WebhookDelivery     WebhookDelivery     `json:"webhook_delivery"`
	PlatformIntegration PlatformIntegration `json:"platform_integration"`
}

func (q *Queries) GetWebhookDeliveryContext(ctx context.Context, id uuid.UUID) (GetWebhookDeliveryContextRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryContext, id)
	var i GetWebhookDeliveryContextRow
	err := row.Scan(
		&i.WebhookDelivery.ID,
		&i.WebhookDelivery.CompanyID,
		&i.WebhookDelivery.PlatformIntegrationID,
		&i.WebhookDelivery.Platform,
		&i.WebhookDelivery.CompanyToken,
		&i.WebhookDelivery.ExternalEventID,
		&i.WebhookDelivery.PayloadHash,
		&i.WebhookDelivery.Signature,
		&i.WebhookDelivery.Headers,
		&i.WebhookDelivery.Payload,
		&i.WebhookDelivery.Status,
		&i.WebhookDelivery.ErrorMessage,
		&i.WebhookDelivery.Retries,
		&i.WebhookDelivery.ReceivedAt,
		&i.WebhookDelivery.QueuedAt,
		&i.WebhookDelivery.ProcessedAt,
		&i.PlatformIntegration.ID,
		&i.PlatformIntegration.CompanyID,
		&i.PlatformIntegration.NicheID,
		&i.PlatformIntegration.Platform,
		&i.PlatformIntegration.Name,
		&i.PlatformIntegration.Active,
		&i.PlatformIntegration.WebhookToken,
		&i.PlatformIntegration.WebhookSecret,
		&i.PlatformIntegration.AccessToken,
		&i.PlatformIntegration.RefreshToken,
		&i.PlatformIntegration.ExternalAccountID,
		&i.PlatformIntegration.Metadata,
		&i.PlatformIntegration.LastSyncedAt,
		&i.PlatformIntegration.CreatedAt,
		&i.PlatformIntegration.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_deliveries
SET status = 'failed',
    error_message = $2,
    retries = retries + 1
WHERE id = $1
`

type MarkWebhookDeliveryFailedParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markWebhookDeliveryProcessed = `-- name: MarkWebhookDeliveryProcessed :exec
UPDATE webhook_deliveries
SET status = 'processed',
    processed_at = now(),
    error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookDeliveryProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryProcessed, id)
	return err
}

const markWebhookDeliveryQueued = `-- name: MarkWebhookDeliveryQueued :exec
UPDATE webhook_deliveries
SET status = 'queued',
    queued_at = now(),
    error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookDeliveryQueued(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryQueued, id)
	return err
}
